### ISSUE TITLE
Firebase Setup for the application

### ISSUE THREAD

**Issue by maheshalyana** [NewTab-Technnologies/Ride-Bhaiya#17]
- [x] Authentication
- [x] Database creation
- [x] #57
- [x] Code base setup

**Comment by tanishq-2208** [comment]
[ushamsharathreddy9999@gmail.com]

**Comment by tanishq-2208** [comment]
[nethivenkatadheeraj@gmail.com]
[sshashank2005@gmail.com]
[pradeepongole2005@gmail.com]
[abhinayganjai@gmail.com]
